export const mobilesData = [
  {
    id: 1,
    name: "Apple iPhone 14 Pro Max 256 ГБ",
    image: require("./assets/phones/1.png"),
    description:
      "У Apple iPhone 14 Pro Max 6,7-дюймовая панель. Пиковая яркость — 2000 нит. Используется небольшой вырез с датчиком фронтальной камеры и системой Face ID. Кроме того, он способен визуально уменьшаться и увеличиваться. Предусмотрен режим Always-on Display (экран всегда включен). Аппаратная основа — A16 Bionic. Это 4-нм SoC с производительным GPU и дополнительным процессором Image Signal processor для повышения качества снимков. Тыльная камера iPhone 14 Pro Max тройная, на 48, 12 и 12 Мп. Ночью iPhone 14 Pro Max снимает в два раза лучше, чем iPhone 13 Pro. Селфи-камера на 12 Мп.",
    rating: 4.5,
    resolution: "2796х1290",
    memory: "256 GB",
    manufacturingScreen: "OLED",
    frequencyScreen: "120 Гц",
    OS: "iOS 16",
    processor: "Apple A16 Bionic",
    coreCount: 6,
    technicalProcess: "4 нм",
    videoCard: "Apple GPU",
    camera: "Sony IMX713, Sony IMX590, Sony IMX803, Sony IMX633",
    cameraCount: 3,
    cameraPixels: "48+12+12 Мп",
    price: "132 399",
  },

  {
    id: 2,
    name: "Xiaomi Redmi Note 10S 128 ГБ",
    image: require("./assets/phones/2.png"),
    description:
      "Смартфон Xiaomi Redmi Note 10S с безрамочным AMOLED-экраном диагональю 6.4 дюйма способен буквально влюбить в себя с первого взгляда. Он облачен в корпус из черного пластика. Дисплей защищен от царапин покрытием Corning Gorilla Glass 3. Любители мобильных игр останутся довольны этим устройством, ведь у него есть процессор на 8 ядер и сразу 6 ГБ оперативной памяти. Это значит, что даже требовательные к ресурсу приложения будут работать шустро и без зависаний. Объем встроенной памяти составляет 128 ГБ. Этого хватает для хранения большого количества необходимого пользователю смартфона Xiaomi Redmi Note 10S софта и файлов. Конфигурация устройства дополнена стереодинамиками. За безопасность и конфиденциальность личных данных отвечает сканер отпечатков пальцев, расположенный сбоку.",
    rating: 4.5,
    resolution: "2400x1080",
    memory: "128 GB",
    manufacturingScreen: "AMOLED",
    frequencyScreen: "60 Гц",
    OS: "Android 11",
    processor: "MediaTek Helio G95",
    coreCount: 8,
    technicalProcess: "12 нм",
    ozu: "6 GB",
    videoCard: "Mali-G76 MC4",
    camera: "GalaxyCore GC02M1, Sony IMX355, OmniVision OV02B, OmniVision OV64B",
    cameraCount: 4,
    cameraPixels: "64+8+2+2 Мп",
    price: "15 999",
  },

  {
    id: 3,
    name: "Xiaomi Redmi Note 10 Pro 128 ГБ",
    image: require("./assets/phones/3.png"),
    description:
      "Смартфон Xiaomi Redmi Note 10 Pro по своему функционалу может соревноваться с самыми топовыми устройствами. Благодаря объему встроенной памяти, составляющему 128 ГБ, в нем можно хранить огромное количество приложений и файлов. Восьмиядерный процессор, 8 ГБ оперативной памяти и графический ускоритель Adreno 618 дают возможность легко проходить самые тяжеловесные мобильные игры. Основная камера модели с разрешением 108+8+5+2 Мп позволяет делать безукоризненное фото для блогов и соцсетей. Рассматривать и редактировать их удобно на AMOLED-экране с разрешением 2400x1080 пикс. Его диагональ составляет 6.67 дюйма. Благодаря встроенному модулю NFC и поддержке бесконтактной технологии оплаты Google Pay у владельца смартфона Xiaomi Redmi Note 10 Pro владельцу не нужно носить с собой банковские карты.",
    rating: 5,
    resolution: "2400x1080",
    memory: "128 GB",
    manufacturingScreen: "AMOLED",
    frequencyScreen: "120 Гц",
    OS: "Android 11",
    processor: "Snapdragon 732G",
    coreCount: 8,
    technicalProcess: "8 нм",
    videoCard: "Adreno 618",
    camera: "GalaxyCore GC02M1B, Samsung HM2, Sony IMX355, OmniVision OV5675",
    cameraCount: 4,
    cameraPixels: "108+8+5+2 Мп",
    price: "22 499",
  },

  {
    id: 4,
    name: "Apple iPhone 13 Pro Max 256 ГБ",
    image: require("./assets/phones/4.png"),
    description:
      "iPhone 13 Pro Max. Грандиозный апгрейд камер Pro. Режим «Киноэффект» делает из видео настоящее кино. Дисплей Super Retina XDR с технологией ProMotion для более быстрого и плавного взаимодействия. A15 Bionic — самый быстрый чип для iPhone. Прочный корпус и самое долгое время работы без подзарядки среди iPhone.",
    rating: 4.5,
    resolution: "2778×1284",
    memory: "256 GB",
    manufacturingScreen: "OLED",
    frequencyScreen: "120 Гц",
    OS: "iOS 15",
    processor: "Apple A15 Bionic",
    coreCount: 6,
    technicalProcess: "5 нм",
    videoCard: "Apple GPU",
    camera: "Sony IMX703, Sony IMX772, Sony IMX713, Sony IMX590",
    cameraCount: 3,
    cameraPixels: "12+12+12 Мп",
    price: "105 599",
  },

  {
    id: 5,
    name: "Apple iPhone 13 Pro Max 128 ГБ",
    image: require("./assets/phones/5.png"),
    description:
      "Даже наиболее требовательных пользователей не оставит равнодушным мощная аппаратная конфигурация и впечатляющие возможности смартфона Apple iPhone 13 Pro Max с объемом встроенной памяти 128 ГБ. Его 6-ядерный процессор продемонстрирует невероятную скорость при загрузке приложений и обработке данных, а ответственность за отображение реалистичного контента возьмет на себя 6.7-дюймовый OLED-дисплей. Не забыл производитель и о камере смартфона Apple iPhone 13 Pro Max. Так, она оснащена 3 объективами, сенсорами Sony IMX703, Sony IMX772, Sony IMX713, Sony IMX590 и вспышкой True Tone – теперь вы начнете создавать действительно профессиональные кадры, независимо от окружающих условий. Сверхточный сканер молниеносно считает контуры лица, обеспечив быструю разблокировку устройства. С технологией Dolby Atmos вы погрузитесь в насыщенное и объемное звучание, напрочь лишенное малейшего эха.",
    rating: 4,
    resolution: "2778x1284",
    memory: "128 GB",
    manufacturingScreen: "OLED",
    frequencyScreen: "120 Гц",
    OS: "iOS 15",
    processor: "Apple A15 Bionic",
    coreCount: 6,
    technicalProcess: "5 нм",
    videoCard: "Apple GPU",
    camera: "Sony IMX703, Sony IMX772, Sony IMX713, Sony IMX590",
    cameraCount: 3,
    cameraPixels: "12+12+12 Мп",
    price: "95 599",
  },

  {
    id: 6,
    name: "Apple iPhone 13 128 ГБ",
    image: require("./assets/phones/6.png"),
    description:
      "iPhone 13. Самая совершенная система двух камер на iPhone. Режим «Киноэффект» делает из видео настоящее кино. Супербыстрый чип A15 Bionic. Неутомимый аккумулятор. Прочный корпус. И еще более яркий дисплей Super Retina XDR.",
    rating: 5,
    resolution: "2532х1170",
    memory: "128 GB",
    manufacturingScreen: "OLED",
    frequencyScreen: "120 Гц",
    OS: "iOS 15",
    processor: "Apple A15 Bionic",
    coreCount: 6,
    technicalProcess: "4 нм",
    videoCard: "Apple GPU",
    camera: "Sony IMX603, Sony IMX372",
    cameraCount: 2,
    cameraPixels: "12+12 Мп",
    price: "64 399",
  },

  {
    id: 7,
    name: "Honor X8 128 ГБ",
    image: require("./assets/phones/7.png"),
    description:
      "В Honor X8 установлен 6.7-дюймовый дисплей формата Full HD+ с частотой обновления 90 Гц. На лицевой панели осталась только одна камера – на 16 Мп. Сзади расположились модули разрешением 64 Мп, 5 Мп, 2 Мп и 2 Мп. Смартфон оснащается 6-нанометровым мобильным процессором Snapdragon 680. Емкость аккумулятора 4000 мА*ч.",
    rating: 3,
    resolution: "2388x1080",
    memory: "128 GB",
    manufacturingScreen: "IPS",
    frequencyScreen: "90 Гц",
    OS: "Android 11",
    processor: "Snapdragon 680",
    coreCount: 8,
    technicalProcess: "6 нм",
    videoCard: "Adreno 610",
    camera: "Sony IMX713, Sony IMX590, Sony IMX803, Sony IMX633",
    cameraCount: 4,
    cameraPixels: "64+5+2+2 Мп",
    price: "15 999",
  },

  {
    id: 8,
    name: "Tecno POVA 4 Pro 256 ГБ",
    image: require("./assets/phones/8.png"),
    description:
      "Емкость батареи составляет 6000 мАч. Даже 20 % заряда аккумулятора хватит на 12 часов телефонных звонков, почти на 3 часа игры и на 4 часа просмотра роликов в интернете. Дополнен аккумулятор функцией быстрой зарядки в 45 Вт, которая позволит вам зарядить смартфон на 50% всего за 24 минуты. В POVA 4 Pro установлен 6.7” AMOLED экран с частотой обновления 90 Гц. Оптимальные размеры и улучшенное качество изображения позволят с комфортом смотреть видео и фильмы в высоком качестве и наслаждаться продвинутой графикой в играх. Многофункциональность смартфона выходит на высокий уровень. В телефоне установлен мощный процессор Helio G99 с улучшенным движком и максимальным объемом памяти 256+8 ГБ. Объем оперативной памяти увеличивается дополнительно виртуальной памятью до +5 ГБ. Теперь вы можете смело выполнять несколько задач одновременно открывая их в дополнительных окнах на экране. Забудьте про лаги и зависания в игре, плавная и быстрая работа смартфона обязательно повысит ваш винрейт в популярных онлайн дисциплинах. Если смартфон для вас не просто средство связи, а полноценное рабочее устройство и вы активно используете его в течение рабочего дня, то POVA 4 Pro создаст необходимые условия для комфортного решения любых задач. А вечером поможет расслабиться за любимой игрой или просмотром интересных фильмов и роликов.",
    rating: 4.5,
    resolution: "2400x1080",
    memory: "256 GB",
    manufacturingScreen: "AMOLED",
    frequencyScreen: "90 Гц",
    OS: "Android 12",
    processor: "MediaTek Helio G99",
    coreCount: 8,
    technicalProcess: "6 нм",
    videoCard: "Mali-G57 MC2",
    camera: "Sony IMX713, Sony IMX590, Sony IMX803",
    cameraCount: 2,
    cameraPixels: "50+2 Мп",
    price: "19 999",
  },

  {
    id: 9,
    name: "Honor 70 256 ГБ",
    image: require("./assets/phones/9.png"),
    description:
      "У Honor 70 6,67-дюймовый OLED-дисплей с разрешением Full HD+ и частотой обновления 120. Тыльная камера тройная — на 54 (датчик Sony IMX800), 50 и 2 Мп. Селфи-камера 32-мегапиксельная. Толщина устройства — 7,91 мм, вес — 178 г. Внутри батарея на 4800 мА*ч с 66-ваттной зарядкой. Работают смартфоны линейки Honor 70 под управлением Android 12 c фирменным интерфейсом Magic UI 6.1.",
    rating: 4,
    resolution: "2400x1080",
    memory: "256 GB",
    manufacturingScreen: "OLED",
    frequencyScreen: "120 Гц",
    OS: "Android 12",
    processor: "Snapdragon 778G Plus",
    coreCount: 8,
    technicalProcess: "6 нм",
    videoCard: "Adreno 642L",
    camera: "Sony IMX800",
    cameraCount: 3,
    cameraPixels: "54+50+2 Мп",
    price: "40 499",
  },

  {
    id: 10,
    name: "Apple iPhone 14 Pro 256 ГБ",
    image: require("./assets/phones/10.png"),
    description:
      "У iPhone 14 Pro 6,1-дюймовая панель. Пиковая яркость — 2000 нит. Используется небольшой вырез с датчиком фронтальной камеры и системой Face ID. Кроме того, он способен визуально уменьшаться и увеличиваться. Предусмотрен режим Always-on Display (экран всегда включен). Аппаратная основа — A16 Bionic. Это 4-нм SoC с производительным GPU и дополнительным процессором Image Signal Processor для повышения качества снимков. Тыльная камера iPhone 14 Pro тройная, на 48, 12 и 12 Мп. Ночью iPhone 14 Pro снимает в два раза лучше, чем iPhone 13 Pro. Селфи-камера на 12 Мп.",
    rating: 4.5,
    resolution: "2556х1179",
    memory: "256 GB",
    manufacturingScreen: "OLED",
    frequencyScreen: "120 Гц",
    OS: "iOS 16",
    processor: "Apple A16 Bionic",
    coreCount: 6,
    technicalProcess: "4 нм",
    videoCard: "Apple GPU",
    camera: "Sony IMX713, Sony IMX590, Sony IMX803, Sony IMX633",
    cameraCount: 3,
    cameraPixels: "48+12+12 Мп",
    price: "121 899",
  },

  {
    id: 11,
    name: '6.53" Смартфон Xiaomi Redmi 9C NFC 64 ГБ серый',
    image: require("./assets/phones/11.png"),
    description:
      "Смартфон Xiaomi Redmi 9C NFC в привлекательном темно-сером корпусе из пластика порадует своего владельца самым прогрессивным функционалом. Его IPS-экран при диагонали 6.53 дюйма отображает картинку с разрешением до 1600x720 пикселей, обеспечивая высокую четкость и детализацию. За быстродействие отвечают процессор на 8 ядер, графическое ядро PowerVR GE8320 и сразу 3 ГБ оперативной памяти. Проходить требовательные игры и работать сразу в нескольких приложениях за счет такой конфигурации можно одинаково шустро.Хранить огромное количество приложений и файлов получится на 64 ГБ собственной памяти смартфона. Основная камеру модели состоит из 2 модулей и обладает разрешением 13+2 Мп. Она оснащена искусственным интеллектом и функцией улучшения изображения. То же самое относится к 5-мегапиксельной фронтальной камере смартфона Xiaomi Redmi 9C NFC. С этим устройством фото, селфи и прямые эфиры будут отличаться непревзойденным качеством!",
    rating: 3,
    resolution: "1600x720",
    memory: "64 GB",
    manufacturingScreen: "IPS",
    frequencyScreen: "60 Гц",
    OS: "Android 10",
    processor: "MediaTek Helio G35",
    coreCount: 8,
    technicalProcess: "12 нм",
    videoCard: "PowerVR GE8320",
    camera: "Sony IMX713, Sony IMX590, Sony IMX633",
    cameraCount: 2,
    cameraPixels: "13+2 Мп",
    price: "6 999",
  },

  {
    id: 12,
    name: '6.7" Смартфон Infinix NOTE 12 PRO 256 ГБ голубой',
    image: require("./assets/phones/12.png"),
    description:
      "Это первый смартфон на чипе MediaTek Helio G99. Infinix NOTE 12 PRO оснащается 6,7-дюймовым AMOLED-экраном с разрешением 2400x1080 пикселей и частотой обновления 60 Гц. Батарея имеет емкость 5000 мАч. Из камер: основная 108 Мп, фронтальная 16 Мп, сенсор глубины 2 Мп и AI Lens. Есть разъем 3,5-мм для наушников, поддержка быстрой зарядки 33 Вт и поддержка бесконтактной оплаты.",
    rating: 4.5,
    resolution: "2400x1080",
    memory: "256 GB",
    manufacturingScreen: "AMOLED",
    frequencyScreen: "90 Гц",
    OS: "Android 12",
    processor: "MediaTek Helio G99",
    coreCount: 8,
    technicalProcess: "6 нм",
    videoCard: "Mali-G57 MC2",
    camera: "Samsung HM6",
    cameraCount: 3,
    cameraPixels: "108+2+0.08 Мп",
    price: "16 999",
  },

  {
    id: 13,
    name: '6.43" Смартфон Xiaomi Redmi Note 11S 128 ГБ голубой',
    image: require("./assets/phones/13.png"),
    description:
      "Смартфон Xiaomi Redmi Note 11S 128 ГБ оснащен дисплеем AMOLED 6.43 дюйма FullHD+ с тонкой рамкой и мощными аппаратными компонентами. Основой данной модели является процессор MediaTek Helio G96, работающий в паре с 6 ГБ ОЗУ для обеспечения высокого уровня производительности. На задней стороне расположены 4 модуля камер 108+8+2+2 Мп, которые позволяют запечатлевать реалистичные фотографии и видео. Спереди расположена камера 16 Мп, при помощи которой можно создавать селфи и общаться по видеосвязи. Мобильное устройство отличается поддержкой двух карт SIM и возможностью расширения внутренней памяти 128 ГБ картой microSD. Широкий набор интерфейсов позволяет быстро синхронизироваться с совместимыми устройствами. Аккумулятор 5000 мА*ч гарантирует длительную автономность Xiaomi Redmi Note 11S и обладает поддержкой функции ускоренной зарядки.",
    rating: 4,
    resolution: "2400x1080",
    memory: "128 GB",
    manufacturingScreen: "AMOLED",
    frequencyScreen: "90 Гц",
    OS: "Android 11",
    processor: "MediaTek Helio G96",
    coreCount: 8,
    technicalProcess: "6 нм",
    videoCard: "Mali-G57 MC2",
    camera: "Samsung HM2, GalaxyCore GC02M1, Sony IMX355, OmniVision OV02B",
    cameraCount: 4,
    cameraPixels: "108+8+2+2 Мп",
    price: "18 499",
  },

  {
    id: 14,
    name: '6.8" Смартфон Samsung Galaxy S22 Ultra 256 ГБ черный',
    image: require("./assets/phones/14.png"),
    description:
      "Samsung Galaxy S22 Ultra получил 6.8-дюймовый AMOLED-дисплей, выполненный по технологии LTPO с разрешением QHD+ и частотой обновления от 1 до 120 Гц. Объем ОЗУ составляет 12 ГБ, емкость накопителя 256 ГБ. Внутри находится батарея на 5000 мА*ч. Мощность быстрой зарядки равна 45 Вт. У смартфона тыльная камера на 108, 12, 10 и 10 Мп. Селфи-камера на 40 Мп. Работает смартфон под управлением Android 12 с фирменной оболочкой One UI 4.0.",
    rating: 5,
    resolution: "3088х1440",
    memory: "256 GB",
    manufacturingScreen: "OLED",
    frequencyScreen: "120 Гц",
    OS: "Android 12",
    processor: "Exynos 2200",
    coreCount: 8,
    technicalProcess: "4 нм",
    videoCard: "Samsung Xclipse 920",
    camera: "Sony IMX563, Samsung ISOCELL HM3, Sony IMX754",
    cameraCount: 4,
    cameraPixels: "108+12+10+10 Мп",
    price: "93 499",
  },

  {
    id: 15,
    name: '6.1" Смартфон Samsung Galaxy S22 256 ГБ черный',
    image: require("./assets/phones/15.png"),
    description:
      "Samsung Galaxy S22 оснащен 6,1-дюймовым дисплеем AMOLED FHD+ с частотой обновления 120 Гц и рекордной яркостью 1750 кд/м2. Для селфи есть 10-мегапиксельная фронтальная камера, а на задней панели располагается 50-мегапиксельная основная камера, 12-мегапиксельный сверхширокоугольный модуль и 10-мегапиксельная телеобъектив. Samsung Galaxy S22 оснащен однокристальной системой Exynos 2200. Устройство имеет 8 ГБ оперативной памяти LPDDR5 и 256 ГБ флеш-памzти UFS 3.1. На устройстве предустановлена операционная система Android 12 на базе One UI 4.0. В нем установлена батарея емкостью 3700 мА•ч, которая поддерживает быструю зарядку 25 Вт.",
    rating: 4,
    resolution: "2400x1080",
    memory: "256 GB",
    manufacturingScreen: "Dynamic AMOLED 2X",
    frequencyScreen: "120 Гц",
    OS: "Android 12",
    processor: "Exynos 2200",
    coreCount: 8,
    technicalProcess: "4 нм",
    videoCard: "Samsung Xclipse 920",
    camera: "Sony IMX772, Sony IMX713, Samsung ISOCELL GN5",
    cameraCount: 3,
    cameraPixels: "50+12+10 Мп",
    price: "64 499",
  },

  {
    id: 16,
    name: '6.62" Смартфон realme GT Neo 3T 256 ГБ черный',
    image: require("./assets/phones/16.png"),
    description:
      "Смартфон realme GT Neo 3T оснащен процессором Snapdragon 870. Он объединяет восемь ядер Kryo 585 с тактовой частотой до 3,2 ГГц, графический ускоритель Adreno 650 и сотовый модем Snapdragon X55 5G. Дисплей имеет размер 6,62 дюйма по диагонали, обладает разрешением Full HD+ и частотой обновления 120 Гц. Обеспечивается 100-процентный охват цветового пространства DCI-P3, а пиковая яркость достигает 1300 кд/м2. Во фронтальной части установлена 16-мегапиксельная селфи-камера. Тыльная камера объединяет 64-мегапиксельный основной блок, 8-мегапиксельный модуль с широкоугольной оптикой и 2-мегапиксельный сенсор для макросъёмки. Смартфон несёт на борту 8 Гбайт оперативной памяти и флеш-накопитель вместимостью 256 Гбайт. Есть адаптеры Wi-Fi 6 и Bluetooth 5.2, контроллер NFC. За питание отвечает аккумуляторная батарея ёмкостью 5000 мА·ч с поддержкой 80-ваттной зарядки.",
    rating: 3,
    resolution: "2400x1080",
    memory: "256 GB",
    manufacturingScreen: "Super AMOLED",
    frequencyScreen: "120 Гц",
    OS: "Android 12",
    processor: "Snapdragon 870 5G",
    coreCount: 8,
    technicalProcess: "7 нм",
    videoCard: "Adreno 650",
    camera: "Sony IMX355, Sony IMX766, Omnivision OV64B",
    cameraCount: 3,
    cameraPixels: "64+8+2 Мп",
    price: "37 999",
  },

  {
    id: 17,
    name: '6.67" Смартфон POCO X4 Pro 5G 256 ГБ синий',
    image: require("./assets/phones/17.png"),
    description:
      "Смартфон POCO X4 Pro 5G 256 ГБ создан для увлекательных мобильных развлечений и отличается мощными камерами для создания реалистичных снимков. В устройстве установлен дисплей 6.67 дюйма AMOLED с поддержкой DCI-P3, который обеспечивает формирование реалистичного изображения кинематографического качества. Высокая производительность системы достигается благодаря взаимодействию процессора Snapdragon 695 и 8 ГБ памяти ОЗУ. Основная камера 108+8+2 Мп при поддержке ряда технологий и функций позволяет делать фотографии и видео высокой четкости. Дополнительно предусмотрена камера 16 Мп на передней стороне. Мобильное устройство обладает поддержкой 5G, слотами под размещение двух карт SIM и интерфейсами беспроводной связи. К особенностям POCO X4 Pro относятся медная тепловая трубка LiquidCool, функции защиты доступа к системе и длительная автономность от аккумулятора 5000 мА*ч.",
    rating: 4,
    resolution: "2400x1080",
    memory: "256 GB",
    manufacturingScreen: "AMOLED",
    frequencyScreen: "120 Гц",
    OS: "Android 11",
    processor: "Snapdragon 695",
    coreCount: 8,
    technicalProcess: "6 нм",
    videoCard: "Adreno 619",
    camera: "Samsung HM2, GalaxyCore GC02M1, Sony IMX355",
    cameraCount: 3,
    cameraPixels: "108+8+2 Мп",
    price: "28 999",
  },

  {
    id: 18,
    name: '6.4" Смартфон realme 9 Pro+ 256 ГБ зеленый',
    image: require("./assets/phones/18.png"),
    description:
      "Смартфон realme 9 Pro+ может похвастаться наличием 6.4-дюймового Super AMOLED-дисплея, который восхитит трансляцией поразительно реалистичного контента с четким отображением малейших деталей – а все благодаря тому, что его разрешение достигает 2400x1080 пикселей. Чтобы сделать памятные кадры впечатляющей насыщенности и детализации, достаточно воспользоваться основной тройной камерой с сенсорами GalaxyCore GC02M1, Sony IMX355, Sony IMX766. Смартфон realme 9 Pro+ оснащен мощным аккумулятором емкостью 4500 мАч, который не нарушит ваших планов внезапно низким уровнем заряда. Внутри выполненного из пластика и стекла корпуса расположился 8-ядерный процессор MediaTek Dimensity 920, который позволит вам насладиться всеми преимуществами молниеносной загрузки приложений и файлов. С технологией распознавания лица и сканером отпечатков пальцев никто из посторонних не получит доступ к личным данным пользователя.",
    rating: 4,
    resolution: "2400x1080",
    memory: "256 GB",
    manufacturingScreen: "Super AMOLED",
    frequencyScreen: "90 Гц",
    OS: "Android 12",
    processor: "Dimensity 920",
    coreCount: 8,
    technicalProcess: "6 нм",
    videoCard: "Mali-G68 MC4",
    camera: "GalaxyCore GC02M1, Sony IMX355, Sony IMX766",
    cameraCount: 3,
    cameraPixels: "50+8+4 Мп",
    price: "27 999",
  },
];

export const usersData = [
  {
    id: 1,
    firstName: "Micke",
    secondName: "Jokovich",
    isAuth: false,
    email: "user@mail.ru",
    password: "123456789",
    token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
    image: "",
  },
  {
    id: 2,
    firstName: "Vasilii",
    secondName: "Pupkin",
    isAuth: false,
    email: "vasya@mail.ru",
    password: "test123456789",
    token:
      "eyJhbGciOiJDAazxXcaAWeqsaInR5cCI6IkpXVCJ9.ejSjdpoaSIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
    image: "",
  },
  {
    id: 3,
    firstName: "Анастасия",
    secondName: "Александровна",
    isAuth: false,
    email: "test@mail.ru",
    password: "123456789",
    token:
      "eyJhbGciOiJDAazxXcaAWeqsaInR5cCI6IkpXVCJ9.ejSjdpoaSIiOiIxMsdouOPIhP12OnjkaO89PTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
    image: "",
  },
];
